# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  rdrkback-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: rdrkback-mysql
    volumes:
      - rdrkback-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rdrkback
      - MYSQL_DATABASE=rdrkback
      - MYSQL_USER=rdrkback
      - MYSQL_PASSWORD=rdrkback

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: rdrkback-app
    volumes:
      - .:/var/www/app
    ports:
      - "81:8080"
    links:
      - mysql
